name: CI

on:
  push:
    branches:
      - "**"

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js and yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
      #  Install dependencies (this will install the dependencies for all workspaces)
      - name: Install dependencies with Yarn
        run: yarn install
  package:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Lint
        run: cd package && yarn run lint
      - name: Build package
        run: yarn run build
  site:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build package
        run: cd site && yarn run build
